### ISSUE TITLE
Errors on Swift 3

### ISSUE THREAD

**Issue by sergeydi** [RobinChao/AnimatedPaths#1]
Hi,

I try to execute your code on swift 3 and get error:
CGPathAddPath is unavailable: Use addPath(_:transform)

How to fix this?

**Comment by Yak0xff** [comment]
Very thanks to report this issue, i have updated the repo to support Swift 3.0. you can update the code to see the lastest code.

**Comment by sergeydi** [comment]
Works perfect. Thank you.
