### ISSUE TITLE
Convert animation to gif

### ISSUE THREAD

**Issue by sergeydi** [RobinChao/AnimatedPaths#2]
May be you know how export animation to gif?

**Comment by Yak0xff** [comment]
1. Record the animation play to video;
2. Convert video to gif.

this is my mind, convert video to gif ,mey be you can see: [Convert video to animated GIF on iOS](http://stackoverflow.com/questions/32446196/convert-video-to-animated-gif-on-ios/39100714)

Thanks.

**Comment by sergeydi** [comment]
Thank you.
