### ISSUE TITLE
Doesn't work for Chinese characters

### ISSUE THREAD

**Issue by objcCodingTogether** [RobinChao/AnimatedPaths#3]
![img_8274](https://user-images.githubusercontent.com/5696017/27010375-9ccfc1ce-4ed5-11e7-893d-070eb92307d4.PNG)

The attache image is the result of "你好Swift!".

Any ideas?
Thanks!

**Comment by Yak0xff** [comment]
I had update project and it's work for Chinese characters. Thanks.

**Comment by objcCodingTogether** [comment]
Thanks Chao!
